---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
  labels:
    app: schema-registry
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    #name: "8081"
  selector:
    app: schema-registry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: schema-registry
  labels:
    app: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      #nodeSelector:
      #  servertype: app
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:5.5.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:  # https://docs.confluent.io/current/schema-registry/installation/config.html
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        #- name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
        #  value: kafkadev-zookeeper-client:2181
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: PLAINTEXT://kafkadev-kafka-bootstrap:9092
        - name: SCHEMA_REGISTRY_HOST_NAME
          #value: localhost
          valueFrom:
            fieldRef:
              fieldPath: status.podIP          
        - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
          value: PLAINTEXT